#!/bin/bash

echo "Install Dependencies"
echo "Install Generic Tools"
# opencv 安装
curl -O https://github.com/opencv/opencv/archive/4.3.0.zip && unzip opencv-4.3.0.zip && mv opencv-4.3.0 opencv && \
curl -O https://github.com/opencv/opencv_contrib/archive/4.3.0.zip && unzip opencv_contrib-4.3.0.zip && mv opencv_contrib-4.3.0 opencv_contrib && \
pushd opencv>&1 > /dev/null && mkdir build && pushd build>&1 > /dev/null && \
cmake -D WITH_QT=ON \
        -D WITH_CUDA=ON \
        -D BUILD_TIFF=ON \
        -D BUILD_TESTS=OFF \
        -D BUILD_PERF_TESTS=OFF \
        -D OPENCV_GENERATE_PKGCONFIG=ON \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ \
        -D BUILD_opencv_xfeatures2d=OFF  .. && \
make -j4 && make -j4 install && pkg-config --cflags opencv4 && echo '/usr/local/lib' > /etc/ld.so.conf.d/opencv.conf && \
popd 2>&1 > /dev/null && popd 2>&1 > /dev/null && rm -rf opencv-4.3.0.zip && rm -rf opencv_contrib-4.3.0.zip"
